// --- 驕主悉蝠上ョ繝ｼ繧ｿ Part 1 (隱槫ｽ吶・譁・ｳ・ ---
const pastDataP1 = [
    { id: "p1_01", type: "choice", q: "We are going to leave for Australia (               ) two weeks.", a: ["of", "in", "by", "with"], correct: 1, exp: "in + 譛滄俣縺ｧ縲後懷ｾ後阪Ｍeave for 縺ｯ縲後懊↓蜷代￠縺ｦ蜃ｺ逋ｺ縺吶ｋ縲阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_02", type: "choice", q: "(               ) almost ten years since I met you in Kyoto.", a: ["It is", "It has passed", "It has", "It was"], correct: 0, exp: "It is [has been] ~ since ... 縺ｧ縲後懊＠縺ｦ縺九ｉ...縺ｫ縺ｪ繧九阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_03", type: "choice", q: "This medicine will do you (               ).", a: ["happy", "comfortable", "effective", "good"], correct: 3, exp: "do A good 縺ｧ縲窟縺ｫ蜉ｹ縺上、縺ｮ縺溘ａ縺ｫ縺ｪ繧九阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_04", type: "choice", q: "While (               ) in London, I visited the National Gallery.", a: ["stay", "stayed", "staying", "to stay"], correct: 2, exp: "While staying... 縺ｮ蠖｢縲ゆｸｻ隱槭→be蜍戊ｩ槭′逵∫払縺輔ｌ縺溷・隧樊ｧ区枚縺ｧ縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_05", type: "choice", q: "Robert is a good scholar, and, (               ), a good teacher.", a: ["not only", "still less", "what is more", "that is"], correct: 2, exp: "what is more縲後◎縺ｮ荳翫√＆繧峨↓縲阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_06", type: "choice", q: "You can listen to music (               ) you like.", a: ["as many as", "as far as", "as long as", "as high as"], correct: 2, exp: "as long as縲後懊☆繧矩剞繧奇ｼ域擅莉ｶ・峨阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_07", type: "choice", q: "I love him none the (               ) for his faults.", a: ["little", "less", "much", "more"], correct: 1, exp: "none the less for ...縲・..縺ｫ繧ゅ°縺九ｏ繧峨★縲√ｄ縺ｯ繧翫阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_08", type: "choice", q: "(               ) your help, I could not have done it.", a: ["But for", "Instead of", "Thanks to", "For all"], correct: 0, exp: "But for ...縲・..縺後↑縺九▲縺溘↑繧峨・縲阪ゆｻｮ螳壽ｳ暮℃蜴ｻ螳御ｺ・・蟶ｰ邨舌・", cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_09", type: "choice", q: "A: How often do you play tennis? B: Every (               ) day.", a: ["one", "other", "another", "each"], correct: 1, exp: "every other day縲・譌･縺翫″縺ｫ縲阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_10", type: "choice", q: "A: Have you reserved a table at the restaurant? B: Not yet. I made a call, but I couldn't (               ) through.", a: ["take", "go", "come", "get"], correct: 3, exp: "get through縲鯉ｼ磯崕隧ｱ縺ｪ縺ｩ縺鯉ｼ峨▽縺ｪ縺後ｋ縲阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_11", type: "choice", q: "The bullet train is (               ) Tokyo Station.", a: ["approaching", "approaching on", "approached", "being approached"], correct: 0, exp: "approach縺ｯ莉門虚隧槭↑縺ｮ縺ｧ蜑咲ｽｮ隧槭・荳崎ｦ√〒縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_12", type: "choice", q: "Please forgive me for (               ) your e-mail.", a: ["not answer", "not to answer", "answering not", "not answering"], correct: 3, exp: "蜍募錐隧槭・蜷ｦ螳壹・ not 繧堤峩蜑阪↓鄂ｮ縺阪∪縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_13", type: "choice", q: "She put up some posters around the church so as (               ) when she will play the guitar.", a: ["to be", "to do", "to help", "to advertise"], correct: 3, exp: "so as to do縲後懊☆繧九◆繧√↓縲阪ょｮ｣莨昴☆繧九・縺ｧ advertise 縺碁←蛻・・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_14", type: "choice", q: "My mother patted me on (               ).", a: ["a shoulder", "shoulders", "the shoulder", "shoulder"], correct: 2, exp: "patted me on the shoulder (霄ｫ菴馴Κ菴阪ｒ縺溘◆縺・縲・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_15", type: "choice", q: "(               ) of my classmates have been to China.", a: ["No", "None", "No one", "Not"], correct: 1, exp: "None of A縲窟縺ｮ縺・■縺ｮ隱ｰ繧ゅ懊↑縺・阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_16", type: "choice", q: "Her experiment resulted in (               ) outcome.", a: ["surprised", "a surprised", "surprising", "a surprising"], correct: 3, exp: "outcome・育ｵ先棡・峨・蜿ｯ邂怜錐隧槭↑縺ｮ縺ｧ a 縺悟ｿ・ｦ√るｩ壹″繧剃ｸ弱∴繧九・縺ｯ surprising縲・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_17", type: "choice", q: "He is still (               ) in bed.", a: ["upstairs", "on upstairs", "in upstairs", "of upstairs"], correct: 0, exp: "upstairs・・髫弱〒・峨・蜑ｯ隧槭↑縺ｮ縺ｧ蜑咲ｽｮ隧槭・荳崎ｦ√〒縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_18", type: "choice", q: "We can see a lot of stars (               ) night in the countryside.", a: ["in", "on", "at", "to"], correct: 2, exp: "at night・亥､懊↓・峨・譎ょ綾縺ｮ譎らせ繧定｡ｨ縺励∪縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_19", type: "choice", q: "(               ) there is a miracle, I won't be able to get a perfect score.", a: ["Although", "If", "Without", "Unless"], correct: 3, exp: "Unless縲後懊＠縺ｪ縺・剞繧翫阪よэ蜻ｳ逧・↓譚｡莉ｶ縺ｨ縺励※驕ｩ蛻・・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_20", type: "choice", q: "If you are in a club, you have to go. But, if not, you (               ) go.", a: ["must", "dare not", "don't have to", "had to"], correct: 2, exp: "don't have to縲後懊☆繧句ｿ・ｦ√・縺ｪ縺・阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_21", type: "choice", q: "How many houses (               ) damaged in the tornado?", a: ["were", "had", "did", "made"], correct: 0, exp: "螳ｶ縺瑚｢ｫ螳ｳ繧貞女縺代◆縺ｨ縺・≧蜿怜虚諷・were damaged縲・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_22", type: "choice", q: "It will take at least two weeks to get this job (               ).", a: ["doing", "does", "being done", "done"], correct: 3, exp: "get + O + done 縺ｧ縲薫繧偵懊＠縺ｦ繧ゅｉ縺・邨ゅｏ繧峨○繧九阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_23", type: "choice", q: "If it (               ) to rain this hard, tonight's game will be canceled.", a: ["keeps", "stays", "continues", "lasts"], correct: 2, exp: "continue to do 縺ｧ縲後懊＠邯壹￠繧九阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_24", type: "choice", q: "The man checked if there were any seats (               ) on the flight.", a: ["available", "frequent", "ridiculous", "successful"], correct: 0, exp: "available縲檎ｩｺ縺・※縺・ｋ縲∝茜逕ｨ蜿ｯ閭ｽ縺ｪ縲阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_25", type: "choice", q: "By the time she finished her work, she (               ) a break three times.", a: ["took", "has taken", "had taken", "will have taken"], correct: 2, exp: "驕主悉縺ｮ縺ゅｋ譎らせ・・inished・峨∪縺ｧ縺ｮ邨碁ｨ薙↑縺ｮ縺ｧ驕主悉螳御ｺ・ｽ｢縲・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_26", type: "choice", q: "Yuka lost her temper (               ) after David spilled coffee.", a: ["presently", "currently", "nearly", "immediately"], correct: 3, exp: "immediately after 縺ｧ縲後懊・逶ｴ蠕後↓縲阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_27", type: "choice", q: "I'm reluctant (               ) it because it wrinkles so easily.", a: ["in wearing", "of wearing", "to wear", "that wears"], correct: 2, exp: "be reluctant to do縲後懊☆繧九・繧貞ｫ後′繧九阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_28", type: "choice", q: "He used to carry his favorite bag with him (               ) he went.", a: ["somewhere", "wherever", "which", "at which"], correct: 1, exp: "wherever縲後懊☆繧九→縺薙ｍ縺ｪ繧峨←縺薙∈縺ｧ繧ゅ阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_29", type: "choice", q: "A (               ) is a punishment in which a person is ordered to pay money.", a: ["law", "cross", "credit", "fine"], correct: 3, exp: "fine 縺ｯ蜷崎ｩ槭〒縲檎ｽｰ驥代阪ｒ諢丞袖縺励∪縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p1_30", type: "choice", q: "You (               ) it, Henry. You worked really hard.", a: ["regret", "deserve", "forget", "miss"], correct: 1, exp: "deserve縲後懊↓蛟､縺吶ｋ縲阪る大ｼｵ縺｣縺溘°繧画ｺ轤ｹ縺ｯ蠖鍋┯縺縲√・諢丞袖縲・, cat: "驕主悉蝠・螟ｧ蝠・" }
];

const pastDataP2 = [
    { id: "p2_01", type: "scramble", jp: "縺ｩ縺・◇縺碑・逕ｱ縺ｫ繧ｳ繝ｼ繝偵・繧偵♀蜿ｬ縺嶺ｸ翫′繧翫￥縺縺輔＞縲・, fixed: ["Please", "."], words: ["some", "coffee", "to", "help", "yourself"], correct: "help yourself to some coffee", exp: "help yourself to ~ 縺ｧ縲後懊ｒ閾ｪ逕ｱ縺ｫ鬟溘∋繧・鬟ｲ繧縲阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p2_02", type: "scramble", jp: "遘√・闍ｱ隱槭ｈ繧翫ｂ繧縺励ｍ繝峨う繝・ｪ槭ｒ蟄ｦ縺ｳ縺溘＞縺ｨ諤昴▲縺ｦ縺・∪縺吶・, fixed: ["I", "English."], words: ["rather", "would", "than", "learn", "German"], correct: "would rather learn German than", exp: "would rather A than B 縺ｧ縲沓繧医ｊ繧縺励ｍA縺励◆縺・阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p2_03", type: "scramble", jp: "蠖ｼ縺ｯ縺昴・莠倶ｻｶ縺ｨ縺ｯ菴輔・髢｢菫ゅｂ縺ゅｊ縺ｾ縺帙ｓ縲・, fixed: ["He has", "case."], words: ["with", "the", "do", "nothing", "to"], correct: "nothing to do with the", exp: "have nothing to do with ~縲後懊→菴輔・髢｢菫ゅｂ縺ｪ縺・阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p2_04", type: "scramble", jp: "遘√ｒ縺縺ｾ縺昴≧縺ｨ縺励※繧ら┌鬧・〒縺吶・, fixed: ["It", "me."], words: ["is", "use", "no", "trying", "to", "deceive"], correct: "is no use trying to deceive", exp: "It is no use ~ing 縺ｧ縲後懊＠縺ｦ繧ら┌鬧・□縲阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p2_05", type: "scramble", jp: "縺薙・繝代Φ繝輔Ξ繝・ヨ繧定ｦ九ｌ縺ｰ縲√◎縺ｮ蟇ｺ縺ｮ讒矩縺後ｈ縺上ｏ縺九ｊ縺ｾ縺吶・, fixed: ["This pamphlet will", "the temple is constructed."], words: ["a good", "idea", "of", "how", "give", "you"], correct: "give you a good idea of how", exp: "give A a good idea of B 縺ｧ縲窟縺ｫB縺ｮ讎りｦ√ｒ繧医￥繧上°繧峨○繧九阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p2_06", type: "scramble", jp: "蜈ｬ蝨偵〒縺昴・迪ｫ繧定ｦ九°縺代◆縺九ｂ縺励ｌ縺ｪ縺・′縲∫｢ｺ縺九〒縺ｯ縺ｪ縺・・, fixed: ["", "the park, but I'm not sure."], words: ["have", "cat", "I", "may", "the", "seen", "in"], correct: "I may have seen the cat in", exp: "may have + p.p. 縺ｧ縲後懊＠縺溘°繧ゅ＠繧後↑縺・阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p2_07", type: "scramble", jp: "繧ゅ≧荳蠎ｦ蛹玲ｵｷ驕薙↓陦後￥縺ｨ縲・蝗櫁｡後▲縺溘％縺ｨ縺ｫ縺ｪ繧九・, fixed: ["I", "I go there again."], words: ["will", "been", "Hokkaido", "five times", "have", "to", "if"], correct: "will have been to Hokkaido five times if", exp: "譛ｪ譚･縺ｮ迚ｹ螳壽凾轤ｹ縺ｧ縺ｮ邨碁ｨ薙ｒ陦ｨ縺呎悴譚･螳御ｺ・ｽ｢縲・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p2_08", type: "scramble", jp: "蜈育函縺ｯ遘√↓縲√ヮ繝・け縺帙★縺ｫ蠖ｼ螂ｳ縺ｮ驛ｨ螻九↓蜈･繧峨↑縺・ｈ縺・↓縺ｨ險縺｣縺溘・, fixed: ["My teacher", "room without knocking."], words: ["to", "me", "not", "told", "come", "her", "into"], correct: "told me not to come into her", exp: "tell A not to do 縺ｧ縲窟縺ｫ縲懊＠縺ｪ縺・ｈ縺・↓險縺・阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p2_09", type: "scramble", jp: "辷ｶ縺ｯ遘√ｒ鬧・〒15蛻・ｾ・◆縺帙◆縲・, fixed: ["My father", "station."], words: ["waiting", "for", "kept", "fifteen minutes", "the", "at", "me"], correct: "kept me waiting for fifteen minutes at the", exp: "keep A waiting 縺ｧ縲窟繧貞ｾ・◆縺帙※縺翫￥縲阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p2_10", type: "scramble", jp: "蠖ｼ螂ｳ縺ｯ1繧ｭ繝ｭ豁ｩ縺九〓縺・■縺ｫ閼壹′逞帙∩蜃ｺ縺励◆縲・, fixed: ["Scarcely", "legs began aching."], words: ["one", "had", "when", "kilometer", "she", "walked", "her"], correct: "had she walked one kilometer when her", exp: "Scarcely + 驕主悉螳御ｺ・蛟堤ｽｮ) ... when 縺ｧ縲後懊☆繧九°縺励↑縺・≧縺｡縺ｫ縲阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p2_11", type: "scramble", jp: "蠖ｼ螂ｳ縺ｯ繝繝ｳ繧ｵ繝ｼ縺縺ｨ險繧上ｌ縺ｦ縺・ｋ縲・, fixed: ["", "."], words: ["It", "is", "said", "that", "she", "is", "a dancer"], correct: "It is said that she is a dancer", exp: "It is said that S+V 縺ｧ縲後懊□縺ｨ險繧上ｌ縺ｦ縺・ｋ縲阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p2_12", type: "scramble", jp: "縺昴・霆翫ｒ雋ｷ縺・・縺ｫ蜊∝・縺ｪ縺企≡縺後≠繧後・繧医°縺｣縺溘・縺ｫ縺ｪ縺ゅ・, fixed: ["", "."], words: ["I", "wish", "I", "had", "had", "enough", "money", "to buy", "the car"], correct: "I wish I had had enough money to buy the car", exp: "I wish + 驕主悉縺ｮ莠句ｮ溘↓蜿阪☆繧矩｡俶悍・井ｻｮ螳壽ｳ暮℃蜴ｻ螳御ｺ・ｼ峨・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p2_13", type: "scramble", jp: "螂ｽ縺阪↑繧ゅ・縺ｯ菴輔〒繧りｲｷ縺｣縺ｦ縺・＞繧医・, fixed: ["", "."], words: ["You", "can", "buy", "whatever", "you", "like"], correct: "You can buy whatever you like", exp: "whatever ~ 縺ｯ縲後懊↑繧ゅ・縺ｯ菴輔〒繧ゅ阪→縺・≧隍・粋髢｢菫ゆｻ｣蜷崎ｩ槭〒縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p2_14", type: "scramble", jp: "繝医Β縺ｯ霑第園縺ｮ莠ｺ縺ｨ縺・∪縺丈ｻ倥″蜷医▲縺ｦ縺・ｋ縲・, fixed: ["Tom", "."], words: ["his", "along", "is getting", "with", "neighbors"], correct: "is getting along with his neighbors", exp: "get along with ~ 縺ｧ縲後懊→縺・∪縺上ｄ縺｣縺ｦ縺・￥縲阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p2_15", type: "scramble", jp: "蠖ｼ縺ｯ遘√・2蛟阪・譛ｬ繧呈戟縺｣縺ｦ縺・ｋ縲・, fixed: ["He has", "as I have."], words: ["as", "many", "books", "twice", "as"], correct: "twice as many books as", exp: "蛟肴焚豈碑ｼ・・ <蛟肴焚隧・+ as ~ as> 縺ｮ隱樣・〒縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" }
];

const pastDataP3 = [
    { id: "p3_01", type: "choice", q: "A: Excuse me. Could you help me?\nB: Sure. What can I do for you?\nA: Do you know where the (               ) to the building is?\nB: The door is right over there.", a: ["elevator", "entrance", "bridge", "stairway"], correct: 1, exp: "B縺ｮ蝗樒ｭ斐後ラ繧｢縺ｯ縺ゅ◎縺薙□縲阪°繧峨悟・繧雁哨縲阪ｒ閨槭＞縺ｦ縺・ｋ縺ｨ繧上°繧翫∪縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p3_02", type: "choice", q: "A: Are you going abroad this summer?\nB: I'd like to, but (               ).\nA: I know what you mean. Airplane tickets cost a lot.\nB: I hope I can save enough money.", a: ["tickets cost a lot", "too dangerous", "allergies are bad", "not sure where"], correct: 0, exp: "A縺ｮ縲瑚穐遨ｺ蛻ｸ縺ｯ鬮倥＞縲阪→縺・≧霑皮ｭ斐°繧峨∬ｲｻ逕ｨ縺ｮ隧ｱ繧偵＠縺ｦ縺・ｋ0逡ｪ縺梧ｭ｣隗｣縲・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p3_03", type: "choice", q: "A: Did you ask your parents about Osaka?\nB: They told me it's (               ) until after my tests.\nA: So, you can't go.\nB: Definitely not.", a: ["possibility", "only thing", "out of the question", "best for me"], correct: 2, exp: "out of the question縲瑚ｫ門､悶∽ｸ榊庄閭ｽ縲阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p3_04", type: "choice", q: "A: It's really raining.\nB: Yes. You should (               ) the river today.\nA: I'll avoid it and take the other road.\nB: Good idea.", a: ["go across", "not go swimming", "take a picture", "stay away from"], correct: 3, exp: "A縺後碁∩縺代ｋ(avoid)縲阪→險縺｣縺ｦ縺・ｋ縺ｮ縺ｧ縲《tay away from縺梧ｭ｣隗｣縲・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p3_05", type: "choice", q: "A: How to use this ticket machine?\nB: Sure. (               )\nA: I need to go to the airport.\nB: OK! Just push this button.", a: ["How to pay?", "Where to go?", "Never used?", "Difficult to buy"], correct: 1, exp: "A縺ｮ霑皮ｭ斐′逶ｮ逧・慍縺ｪ縺ｮ縺ｧ縲∫岼逧・慍繧貞ｰ九・繧玖ｳｪ蝠上ｒ驕ｸ縺ｳ縺ｾ縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p3_06", type: "choice", q: "A: Where is that fish from?\nB: Tokushima. I try to buy local food.\nA: (               )\nB: Less distance means less impact on the environment.", a: ["Like fish?", "Is it famous?", "Problems?", "Why do you do that?"], correct: 3, exp: "逅・罰繧定ｪｬ譏弱＠縺ｦ縺・ｋ縺ｮ縺ｧ縲∫炊逕ｱ繧貞撫縺・ｳｪ蝠上′驕ｩ蛻・・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p3_07", type: "choice", q: "A: Keiko, what's wrong?\nB: I lost the book you lent me.\nA: Don't worry. (               )\nB: Are you sure?", a: ["Need it for test", "Buy new one", "Have another copy", "Important book"], correct: 2, exp: "縲悟ｿ・・縺励↑縺・〒縲阪→郢九′繧狗炊逕ｱ縲後ｂ縺・ｸ蜀翫≠繧九阪′豁｣隗｣縲・, cat: "驕主悉蝠・螟ｧ蝠・" },
    { id: "p3_08", type: "choice", q: "A: What to do after graduation?\nB: Travel around Europe.\nA: (               )\nB: I hope to visit museums for free.", a: ["Why Europe?", "Good place?", "Been to America", "When leave?"], correct: 0, exp: "蜍墓ｩ溘ｒ閨槭￥雉ｪ蝠上↓蟇ｾ縺励∫岼逧・ｒ遲斐∴縺ｦ縺・∪縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" }
];

function b(num) { return `<span class="blank-marker">${num}</span>`; }
function u(text, num) { return `<span class="underline-marker">${text}</span><span class="ref-num">${num}</span>`; }

const pastDataP4 = [
    {
        id: "p4_01",
        passage: `Do you use the Internet for shopping? It is certainly convenient. ${b('竭')} on some websites, popular items are often sold out. Products might be sold out because of people ${b('竭｡')} resellers. Resellers buy products at normal prices and then sell them later for higher prices. ${u('They', '竭｢')} will resell anything, but popular categories for ${b('竭｣')} are sneakers, trading cards, smartphones and toys.\n\nIn recent years, more and more people are reselling items. For some people, it is a full-time job and they can make a lot of money. Is reselling a positive or negative thing? This is a difficult question and many people have strong opinions about it. ${b('竭､')} most people are against reselling. They think that resellers buy products only to make a ${u('profit', '竭･')} not to use themselves. When ordinary people try to buy an item, it is already sold out. The only option is to pay a higher price on a flea market app.\n\nOn the other hand, some people think that resellers provide a valuable service. ${b('竭ｦ')} when a popular new product is sold, people line up outside the shop to buy it. But for most of us, lining up is impossible窶背e are too busy with work or school. However, if resellers line up, buy ${u('the item', '竭ｧ')} and then resell later, we have a chance to get the item, although the price is higher of course.\n\nWhat do you think? Are you for or against reselling? (竭ｨ)\n\n<div class="annotation-box">ordinary・壽勸騾壹・ / flea market app・壹ヵ繝ｪ繝槭い繝励Μ</div>`,
        questions: [
            { id: "p4_01_1", type: "choice", q: "(1) 遨ｺ謇 竭, 竭､, 竭ｦ 縺ｫ蜈･繧矩←蛻・↑隱槭・邨・∩蜷医ｏ縺帙ｒ驕ｸ縺ｹ縲・, a: ["竭 however / 竭､ Probably / 竭ｦ For example", "竭 therefore / 竭､ Usually / 竭ｦ Thus", "竭 however / 竭､ Therefore / 竭ｦ However", "竭 instead / 竭､ Probably / 竭ｦ Thus"], correct: 0, exp: "譁・ц蛻､譁ｭ蝠城｡後や蔵騾・磁 竭､謗ｨ貂ｬ 竭ｦ萓狗､ｺ 縺ｧ縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
            { id: "p4_01_2", type: "choice", q: "(2) 遨ｺ謇 竭｡, 竭｣ 縺ｫ蜈･繧句虚隧槭・驕ｩ蛻・↑蠖｢縺ｮ邨・∩蜷医ｏ縺帙ｒ驕ｸ縺ｹ縲・, a: ["竭｡ calling / 竭｣ reselling", "竭｡ called / 竭｣ reselling", "竭｡ called / 竭｣ resold", "竭｡ calling / 竭｣ resell"], correct: 1, exp: "竭｡蜻ｼ縺ｰ繧後※縺・ｋ莠ｺ縲・called) 竭｣霆｢螢ｲ縺吶ｋ縺薙→(reselling)縺ｮ縺溘ａ縲・, cat: "驕主悉蝠・螟ｧ蝠・" },
            { id: "p4_01_3", type: "choice", q: "(3) 荳狗ｷ夐Κ 竭｢ They 縺ｮ謖・☆蜀・ｮｹ縺ｨ 竭ｧ the item 縺ｮ蜈ｷ菴鍋噪縺ｪ蜊倩ｪ樊焚繧帝∈縺ｹ縲・, a: ["竭｢ Resellers (1隱・ / 竭ｧ a popular new product (4隱・", "竭｢ Websites (1隱・ / 竭ｧ flea market app (3隱・", "竭｢ Products (1隱・ / 竭ｧ a lot of money (4隱・", "竭｢ Toys (1隱・ / 竭ｧ sneakers and cards (3隱・"], correct: 0, exp: "謖・＠遉ｺ縺怜撫鬘後３esellers 縺ｨ a popular new product 繧呈欠縺励∪縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
            { id: "p4_01_4", type: "choice", q: "(4) 荳狗ｷ夐Κ 竭･ profit 縺ｮ諢丞袖縺ｨ縺励※驕ｩ蛻・↑繧ゅ・繧帝∈縺ｹ縲・, a: ["閾ｪ諷｢", "莨∫判", "貅雜ｳ", "蛻ｩ逶・], correct: 3, exp: "make a profit 縺ｧ縲悟茜逶翫ｒ縺ゅ￡繧九阪・, cat: "驕主悉蝠・螟ｧ蝠・" },
            { id: "p4_01_5", type: "choice", q: "(5) 譛ｬ譁・・蜀・ｮｹ縺ｨ荳閾ｴ縺吶ｋ繧ゅ・縺ｯ縺ｩ繧後°縲・, a: ["Resellers buy unpopular items at lower prices.", "Some items might be sold out because of resellers.", "Food products are popular and easy to resell.", "Most people are for reselling."], correct: 1, exp: "隨ｬ1谿ｵ關ｽ縺ｮ蜀・ｮｹ縺ｨ荳閾ｴ縺励∪縺吶ゆｻ悶・險倩ｿｰ縺ｫ蜿阪＠縺ｾ縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" }
        ]
    },
    {
        id: "p4_02",
        passage: `Though the construction industry has traditionally been seen as a man's world, ${u('the government and construction industry organizations are trying to make construction sites more woman-friendly', '竭')}.\n\nIzumi Yamaguchi, 28, an employee of Shimizu Corp., works as a supervisor at a construction site... Among 16 supervisors at the building site, Yamaguchi is the only woman. ${b('竭｡')} Yamaguchi wears a helmet, steel-toed shoes and a safety belt ${u('equipped with', '竭｢')} a lifeline and other items around her waist.\n\nGeneral contractors have been making efforts to improve working conditions at construction sites by, for example, providing bathrooms and changing rooms ${u('exclusively', '竭｣')} for women. They also have begun reforming personnel management systems... Kajima Corp. holds career consultations for female engineers. Junko Tsuchiyama, an official ${b('竭､')} the ${u('promotion', '竭･')} of diversity, said, "At today's more mechanized construction sites, women can play a larger role..."\n\n<div class="annotation-box">construction site・壼ｻｺ險ｭ迴ｾ蝣ｴ / supervisor・夂屮逹｣ / personnel affairs・壻ｺｺ莠・/div>`,
        questions: [
            { id: "p4_02_1", type: "choice", q: "(1) 荳狗ｷ夐Κ 竭 縺ｫ髢｢縺励※莨∵･ｭ縺後＠縺ｦ縺・ｋ蜉ｪ蜉帙・蜈ｷ菴謎ｾ九→縺励※驕ｩ蛻・↑繧ゅ・縺ｯ・・, a: ["螂ｳ諤ｧ蟆ら畑縺ｮ繝医う繝ｬ繧・峩陦｣螳､縺ｮ險ｭ鄂ｮ", "螂ｳ諤ｧ縺ｮ縺ｿ縺ｮ蟒ｺ險ｭ迴ｾ蝣ｴ縺ｮ菴懈・", "邨ｦ荳弱・蛟榊｢苓ｨ育判", "逕ｷ諤ｧ菴懈･ｭ蜩｡縺ｮ蜑頑ｸ・], correct: 0, exp: "譛ｬ譁・↓縲継roviding bathrooms and changing rooms exclusively for women縲阪→縺ゅｊ縺ｾ縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
            { id: "p4_02_2", type: "choice", q: "(2) 遨ｺ謇 竭｡, 竭､ 縺ｫ蜈･繧区怙繧る←蠖薙↑繧ゅ・縺ｯ・・, a: ["竭｡ On the job / 竭､ in charge of", "竭｡ In operation / 竭､ in terms of", "竭｡ While running / 竭､ in spite of", "竭｡ On the job / 竭､ in spite of"], correct: 0, exp: "迴ｾ蝣ｴ莉穂ｺ倶ｸｭ・・n the job・峨→縲√懊・諡・ｽ難ｼ・n charge of・峨〒縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
            { id: "p4_02_3", type: "choice", q: "(3) 荳狗ｷ夐Κ 竭｢, 竭｣, 竭･ 縺ｨ蜈･繧梧崛縺医※繧ゅ⊇縺ｼ蜷後§諢丞袖縺ｫ縺ｪ繧九ｂ縺ｮ縺ｯ・・, a: ["竭｢ complete with / 竭｣ entirely / 竭･ elevation", "竭｢ occupied with / 竭｣ individually / 竭･ publicity", "竭｢ complete with / 竭｣ additionally / 竭･ elevation", "竭｢ in accordance with / 竭｣ entirely / 竭･ advertisement"], correct: 0, exp: "隱槫ｽ吶・險縺・鋤縺亥撫鬘後〒縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
            { id: "p4_02_4", type: "choice", q: "(4) 荳狗ｷ夐Κ 竭ｦ・郁ｨ倩ｿｰ・峨・螟牙喧縺ｮ蜀・ｮｹ縺ｨ縺励※豁｣縺励＞隕∫ｴ・・・・, a: ["蜒阪″譁ｹ繧貞､峨∴繧九％縺ｨ縺ｧ逕ｷ諤ｧ繧ょｿｫ驕ｩ縺ｫ縺ｪ繧頑･ｭ逡後う繝｡繝ｼ繧ｸ縺悟髄荳翫☆繧・, "螂ｳ諤ｧ縺縺代′蠢ｫ驕ｩ縺ｫ縺ｪ繧後・讌ｭ逡後う繝｡繝ｼ繧ｸ縺悟髄荳翫☆繧・, "讖滓｢ｰ蛹悶′騾ｲ繧縺薙→縺ｧ莠ｺ髢薙′荳崎ｦ√↓縺ｪ繧翫う繝｡繝ｼ繧ｸ縺悟髄荳翫☆繧・, "蟄蝉ｾ帙ｒ閧ｲ縺ｦ繧句･ｳ諤ｧ縺縺代ｒ蜆ｪ驕・☆繧・], correct: 0, exp: "蝨溷ｱｱ縺輔ｓ縺ｮ逋ｺ險縺ｮ蠕悟濠驛ｨ蛻・ｒ縺ｾ縺ｨ繧√◆蜀・ｮｹ縺ｧ縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" }
        ]
    },
    {
        id: "p4_03",
        passage: `Do you know what your core values are? Core values are ${u('attributes', '竭')} that are very important to you. For example, if you have a ${u('burning', '竭｡')} desire to be number one, then working hard, doing your best, and ( 竭｢ ) are likely to be some of your core values...\n\n"Here are the values that I ${u('stand for', '竭｣')}: honesty, equality, kindness, compassion, treating people the way you want to be treated, and ( 竭､ ). To me, those are traditional values."\n\nYou can discover your own core values by asking yourself questions... Another way to discover your values is to look at what you do not like. For example, if you become irritated when people are late, then being on time, or ${b('竭･')} is one of your values. If seeing someone being bullied makes you angry, then compassion and ${b('竭ｦ')} are important to you.\n\n<div class="annotation-box">attribute・夂音諤ｧ / punctuality・壽凾髢薙ｒ螳医ｋ縺薙→ / fairness・壼・豁｣縺・/div>`,
        questions: [
            { id: "p4_03_1", type: "choice", q: "(1) 荳狗ｷ夐Κ 竭, 竭｡, 竭｣ 縺ｨ縺ｻ縺ｼ蜷後§諢丞袖繧定｡ｨ縺呵ｪ槭・邨・∩蜷医ｏ縺帙・・・, a: ["竭 characteristics / 竭｡ passionate / 竭｣ support", "竭 dreams / 竭｡ passionate / 竭｣ mean", "竭 characteristics / 竭｡ flaming / 竭｣ endure", "竭 virtues / 竭｡ aching / 竭｣ support"], correct: 0, exp: "竭螻樊ｧ 竭｡諠・・逧・↑ 竭｣謾ｯ謖√☆繧具ｼ育炊蠢ｵ縺ｨ縺吶ｋ・峨〒縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
            { id: "p4_03_2", type: "choice", q: "(2)(3) 遨ｺ謇 竭｢, 竭､, 竭･, 竭ｦ 縺ｫ蜈･繧玖ｪ槫唱縺ｮ邨・∩蜷医ｏ縺帙・・・, a: ["竭｢ achieving success / 竭､ helping those in need / 竭･ punctuality / 竭ｦ fairness", "竭｢ reducing wastes / 竭､ achieving success / 竭･ excitement / 竭ｦ honesty", "竭｢ achieving success / 竭､ honesty / 竭･ punctuality / 竭ｦ excitement", "竭｢ working hard / 竭､ helping those / 竭･ fairness / 竭ｦ punctuality"], correct: 0, exp: "譁・ц縺ｨ縲∵枚譛ｫ縺ｮ豕ｨ驥医ｂ蜿り・↓蛻､譁ｭ縺励∪縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
            { id: "p4_03_3", type: "choice", q: "(4) 譛蛻昴↓霑ｰ縺ｹ繧峨ｌ縺ｦ縺・ｋ萓｡蛟､隕ｳ繧堤衍繧区婿豕輔・・・, a: ["蟄蝉ｾ帙・鬆・･ｽ縺阪□縺｣縺溘％縺ｨ縺ｪ縺ｩ繧定・蛻・↓蝠上＞縺九￠繧・, "雖後＞縺ｪ繧ゅ・繧偵Μ繧ｹ繝医い繝・・縺吶ｋ", "莉紋ｺｺ縺ｮ萓｡蛟､隕ｳ繧堤悄莨ｼ縺励※縺ｿ繧・, "遉ｾ莨壹・譛溷ｾ・↓蠢懊∴繧区ｱｺ譁ｭ繧偵☆繧・], correct: 0, exp: "隨ｬ3谿ｵ關ｽ縺ｮ蜀帝ｭ縺ｫ縲慧iscovery by asking yourself questions縲阪→縺ゅｊ縺ｾ縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" },
            { id: "p4_03_4", type: "choice", q: "(5) 逶ｮ讓吶ｄ豎ｺ譁ｭ縺ｯ菴輔↓蝓ｺ縺･縺・※縺吶∋縺阪→霑ｰ縺ｹ繧峨ｌ縺ｦ縺・ｋ縺具ｼ・, a: ["閾ｪ蛻・・譬ｸ縺ｨ縺ｪ繧倶ｾ｡蛟､隕ｳ(Core values)", "遉ｾ莨壹・譛溷ｾ・, "蜻ｨ蝗ｲ縺ｮ莠ｺ縺ｮ諢剰ｦ・, "譛譁ｰ縺ｮ繝医Ξ繝ｳ繝・], correct: 0, exp: "譛邨よｮｵ關ｽ縺ｫ縲桑nowing your own core values will help to guide your actions縲阪→縺ゅｊ縺ｾ縺吶・, cat: "驕主悉蝠・螟ｧ蝠・" }
        ]
    }
];


