const pastDataP1 = [
            { id: "p1_01", type: "choice", q: "We are going to leave for Australia (               ) two weeks.", a: ["of", "in", "by", "with"], correct: 1, exp: "in + 期間で「〜後」。leave for は「〜に向けて出発する」。", cat: "過去問 大問1" },
            { id: "p1_02", type: "choice", q: "(               ) almost ten years since I met you in Kyoto.", a: ["It is", "It has passed", "It has", "It was"], correct: 0, exp: "It is [has been] ~ since ... で「〜してから...になる」。", cat: "過去問 大問1" },
            { id: "p1_03", type: "choice", q: "This medicine will do you (               ).", a: ["happy", "comfortable", "effective", "good"], correct: 3, exp: "do A good で「Aに効く、Aのためになる」。", cat: "過去問 大問1" },
            { id: "p1_04", type: "choice", q: "While (               ) in London, I visited the National Gallery.", a: ["stay", "stayed", "staying", "to stay"], correct: 2, exp: "While staying... の形。主語とbe動詞が省略された分詞構文です。", cat: "過去問 大問1" },
            { id: "p1_05", type: "choice", q: "Robert is a good scholar, and, (               ), a good teacher.", a: ["not only", "still less", "what is more", "that is"], correct: 2, exp: "what is more「その上、さらに」。", cat: "過去問 大問1" },
            { id: "p1_06", type: "choice", q: "You can listen to music (               ) you like.", a: ["as many as", "as far as", "as long as", "as high as"], correct: 2, exp: "as long as「〜する限り（条件）」。", cat: "過去問 大問1" },
            { id: "p1_07", type: "choice", q: "I love him none the (               ) for his faults.", a: ["little", "less", "much", "more"], correct: 1, exp: "none the less for ...「...にもかかわらず、やはり」。", cat: "過去問 大問1" },
            { id: "p1_08", type: "choice", q: "(               ) your help, I could not have done it.", a: ["But for", "Instead of", "Thanks to", "For all"], correct: 0, exp: "But for ...「...がなかったならば」。仮定法過去完了の帰結。 ", cat: "過去問 大問1" },
            { id: "p1_09", type: "choice", q: "A: How often do you play tennis? B: Every (               ) day.", a: ["one", "other", "another", "each"], correct: 1, exp: "every other day「1日おきに」。", cat: "過去問 大問1" },
            { id: "p1_10", type: "choice", q: "A: Have you reserved a table at the restaurant? B: Not yet. I made a call, but I couldn't (               ) through.", a: ["take", "go", "come", "get"], correct: 3, exp: "get through「（電話などが）つながる」。", cat: "過去問 大問1" },
            { id: "p1_11", type: "choice", q: "The bullet train is (               ) Tokyo Station.", a: ["approaching", "approaching on", "approached", "being approached"], correct: 0, exp: "approachは他動詞なので前置詞は不要です。", cat: "過去問 大問1" },
            { id: "p1_12", type: "choice", q: "Please forgive me for (               ) your e-mail.", a: ["not answer", "not to answer", "answering not", "not answering"], correct: 3, exp: "動名詞の否定は not を直前に置きます。", cat: "過去問 大問1" },
            { id: "p1_13", type: "choice", q: "She put up some posters around the church so as (               ) when she will play the guitar.", a: ["to be", "to do", "to help", "to advertise"], correct: 3, exp: "so as to do「〜するために」。宣伝するので advertise が適切。", cat: "過去問 大問1" },
            { id: "p1_14", type: "choice", q: "My mother patted me on (               ).", a: ["a shoulder", "shoulders", "the shoulder", "shoulder"], correct: 2, exp: "patted me on the shoulder (身体部位をたたく)。", cat: "過去問 大問1" },
            { id: "p1_15", type: "choice", q: "(               ) of my classmates have been to China.", a: ["No", "None", "No one", "Not"], correct: 1, exp: "None of A「Aのうちの誰も〜ない」。", cat: "過去問 大問1" },
            { id: "p1_16", type: "choice", q: "Her experiment resulted in (               ) outcome.", a: ["surprised", "a surprised", "surprising", "a surprising"], correct: 3, exp: "outcome（結果）は可算名詞なので a が必要。驚きを与えるのは surprising。", cat: "過去問 大問1" },
            { id: "p1_17", type: "choice", q: "He is still (               ) in bed.", a: ["upstairs", "on upstairs", "in upstairs", "of upstairs"], correct: 0, exp: "upstairs（2階で）は副詞なので前置詞は不要です。", cat: "過去問 大問1" },
            { id: "p1_18", type: "choice", q: "We can see a lot of stars (               ) night in the countryside.", a: ["in", "on", "at", "to"], correct: 2, exp: "at night（夜に）は時刻の時点を表します。", cat: "過去問 大問1" },
            { id: "p1_19", type: "choice", q: "(               ) there is a miracle, I won't be able to get a perfect score.", a: ["Although", "If", "Without", "Unless"], correct: 3, exp: "Unless「〜しない限り」。意味的に条件として適切。", cat: "過去問 大問1" },
            { id: "p1_20", type: "choice", q: "If you are in a club, you have to go. But, if not, you (               ) go.", a: ["must", "dare not", "don't have to", "had to"], correct: 2, exp: "don't have to「〜する必要はない」。", cat: "過去問 大問1" },
            { id: "p1_21", type: "choice", q: "How many houses (               ) damaged in the tornado?", a: ["were", "had", "did", "made"], correct: 0, exp: "家が被害を受けたという受動態 were damaged。", cat: "過去問 大問1" },
            { id: "p1_22", type: "choice", q: "It will take at least two weeks to get this job (               ).", a: ["doing", "does", "being done", "done"], correct: 3, exp: "get + O + done で「Oを〜してもらう/終わらせる」。", cat: "過去問 大問1" },
            { id: "p1_23", type: "choice", q: "If it (               ) to rain this hard, tonight's game will be canceled.", a: ["keeps", "stays", "continues", "lasts"], correct: 2, exp: "continue to do で「〜し続ける」。", cat: "過去問 大問1" },
            { id: "p1_24", type: "choice", q: "The man checked if there were any seats (               ) on the flight.", a: ["available", "frequent", "ridiculous", "successful"], correct: 0, exp: "available「空いている、利用可能な」。", cat: "過去問 大問1" },
            { id: "p1_25", type: "choice", q: "By the time she finished her work, she (               ) a break three times.", a: ["took", "has taken", "had taken", "will have taken"], correct: 2, exp: "過去のある時点（finished）までの経験なので過去完了形。", cat: "過去問 大問1" },
            { id: "p1_26", type: "choice", q: "Yuka lost her temper (               ) after David spilled coffee.", a: ["presently", "currently", "nearly", "immediately"], correct: 3, exp: "immediately after で「〜の直後に」。", cat: "過去問 大問1" },
            { id: "p1_27", type: "choice", q: "I'm reluctant (               ) it because it wrinkles so easily.", a: ["in wearing", "of wearing", "to wear", "that wears"], correct: 2, exp: "be reluctant to do「〜するのを嫌がる」。", cat: "過去問 大問1" },
            { id: "p1_28", type: "choice", q: "He used to carry his favorite bag with him (               ) he went.", a: ["somewhere", "wherever", "which", "at which"], correct: 1, exp: "wherever「〜するところならどこへでも」。", cat: "過去問 大問1" },
            { id: "p1_29", type: "choice", q: "A (               ) is a punishment in which a person is ordered to pay money.", a: ["law", "cross", "credit", "fine"], correct: 3, exp: "fine は名詞で「罰金」を意味します。", cat: "過去問 大問1" },
            { id: "p1_30", type: "choice", q: "You (               ) it, Henry. You worked really hard.", a: ["regret", "deserve", "forget", "miss"], correct: 1, exp: "deserve「〜に値する」。頑張ったから満点は当然だ、の意味。", cat: "過去問 大問1" }
        ];

        const pastDataP2 = [
            { id: "p2_01", type: "scramble", jp: "どうぞご自由にコーヒーをお召し上がりください。", fixed: ["Please", "."], words: ["some", "coffee", "to", "help", "yourself"], correct: "help yourself to some coffee", exp: "help yourself to ~ で「〜を自由に食べる/飲む」。", cat: "過去問 大問2" },
            { id: "p2_02", type: "scramble", jp: "私は英語よりもむしろドイツ語を学びたいと思っています。", fixed: ["I", "English."], words: ["rather", "would", "than", "learn", "German"], correct: "would rather learn German than", exp: "would rather A than B で「BよりむしろAしたい」。", cat: "過去問 大問2" },
            { id: "p2_03", type: "scramble", jp: "彼はその事件とは何の関係もありません。", fixed: ["He has", "case."], words: ["with", "the", "do", "nothing", "to"], correct: "nothing to do with the", exp: "have nothing to do with ~「〜と何の関係もない」。", cat: "過去問 大問2" },
            { id: "p2_04", type: "scramble", jp: "私をだまそうとしても無駄です。", fixed: ["It", "me."], words: ["is", "use", "no", "trying", "to", "deceive"], correct: "is no use trying to deceive", exp: "It is no use ~ing で「〜しても無駄だ」。", cat: "過去問 大問2" },
            { id: "p2_05", type: "scramble", jp: "このパンフレットを見れば、その寺の構造がよくわかります。", fixed: ["This pamphlet will", "the temple is constructed."], words: ["a good", "idea", "of", "how", "give", "you"], correct: "give you a good idea of how", exp: "give A a good idea of B で「AにBの概要をよくわからせる」。", cat: "過去問 大問2" },
            { id: "p2_06", type: "scramble", jp: "公園でその猫を見かけたかもしれないが、確かではない。", fixed: ["", "the park, but I'm not sure."], words: ["have", "cat", "I", "may", "the", "seen", "in"], correct: "I may have seen the cat in", exp: "may have + p.p. で「〜したかもしれない」。", cat: "過去問 大問2" },
            { id: "p2_07", type: "scramble", jp: "もう一度北海道に行くと、5回行ったことになる。", fixed: ["I", "I go there again."], words: ["will", "been", "Hokkaido", "five times", "have", "to", "if"], correct: "will have been to Hokkaido five times if", exp: "未来の特定時点での経験を表す未来完了形。", cat: "過去問 大問2" },
            { id: "p2_08", type: "scramble", jp: "先生は私に、ノックせずに彼女の部屋に入らないようにと言った。", fixed: ["My teacher", "room without knocking."], words: ["to", "me", "not", "told", "come", "her", "into"], correct: "told me not to come into her", exp: "tell A not to do で「Aに〜しないように言う」。", cat: "過去問 大問2" },
            { id: "p2_09", type: "scramble", jp: "父は私を駅で15分待たせた。", fixed: ["My father", "station."], words: ["waiting", "for", "kept", "fifteen minutes", "the", "at", "me"], correct: "kept me waiting for fifteen minutes at the", exp: "keep A waiting で「Aを待たせておく」。", cat: "過去問 大問2" },
            { id: "p2_10", type: "scramble", jp: "彼女は1キロ歩かぬうちに脚が痛み出した。", fixed: ["Scarcely", "legs began aching."], words: ["one", "had", "when", "kilometer", "she", "walked", "her"], correct: "had she walked one kilometer when her", exp: "Scarcely + 過去完了(倒置) ... when で「〜するかしないうちに」。", cat: "過去問 大問2" },
            { id: "p2_11", type: "scramble", jp: "彼女はダンサーだと言われている。", fixed: ["", "."], words: ["It", "is", "said", "that", "she", "is", "a dancer"], correct: "It is said that she is a dancer", exp: "It is said that S+V で「〜だと言われている」。", cat: "過去問 大問2" },
            { id: "p2_12", type: "scramble", jp: "その車を買うのに十分なお金があればよかったのになあ。", fixed: ["", "."], words: ["I", "wish", "I", "had", "had", "enough", "money", "to buy", "the car"], correct: "I wish I had had enough money to buy the car", exp: "I wish + 過去の事実に反する願望（仮定法過去完了）。", cat: "過去問 大問2" },
            { id: "p2_13", type: "scramble", jp: "好きなものは何でも買っていいよ。", fixed: ["", "."], words: ["You", "can", "buy", "whatever", "you", "like"], correct: "You can buy whatever you like", exp: "whatever ~ は「〜なものは何でも」という複合関係代名詞です。", cat: "過去問 大問2" },
            { id: "p2_14", type: "scramble", jp: "トムは近所の人とうまく付き合っている。", fixed: ["Tom", "."], words: ["his", "along", "is getting", "with", "neighbors"], correct: "is getting along with his neighbors", exp: "get along with ~ で「〜とうまくやっていく」。", cat: "過去問 大問2" },
            { id: "p2_15", type: "scramble", jp: "彼は私の2倍の本を持っている。", fixed: ["He has", "as I have."], words: ["as", "many", "books", "twice", "as"], correct: "twice as many books as", exp: "倍数比較は <倍数詞 + as ~ as> の語順です。", cat: "過去問 大問2" }
        ];

        const pastDataP3 = [
            { id: "p3_01", type: "choice", q: "A: Excuse me. Could you help me?\nB: Sure. What can I do for you?\nA: Do you know where the (               ) to the building is?\nB: The door is right over there.", a: ["elevator", "entrance", "bridge", "stairway"], correct: 1, exp: "Bの回答「ドアはあそこだ」から「入り口」を聞いているとわかります。", cat: "過去問 大問3" },
            { id: "p3_02", type: "choice", q: "A: Are you going abroad this summer?\nB: I'd like to, but (               ).\nA: I know what you mean. Airplane tickets cost a lot.\nB: I hope I can save enough money.", a: ["tickets cost a lot", "too dangerous", "allergies are bad", "not sure where"], correct: 0, exp: "Aの「航空券は高い」という返答から、費用の話をしている0番が正解。", cat: "過去問 大問3" },
            { id: "p3_03", type: "choice", q: "A: Did you ask your parents about Osaka?\nB: They told me it's (               ) until after my tests.\nA: So, you can't go.\nB: Definitely not.", a: ["possibility", "only thing", "out of the question", "best for me"], correct: 2, exp: "out of the question「論外、不可能」。", cat: "過去問 大問3" },
            { id: "p3_04", type: "choice", q: "A: It's really raining.\nB: Yes. You should (               ) the river today.\nA: I'll avoid it and take the other road.\nB: Good idea.", a: ["go across", "not go swimming", "take a picture", "stay away from"], correct: 3, exp: "Aが「避ける(avoid)」と言っているので、stay away fromが正解。", cat: "過去問 大問3" },
            { id: "p3_05", type: "choice", q: "A: How to use this ticket machine?\nB: Sure. (               )\nA: I need to go to the airport.\nB: OK! Just push this button.", a: ["How to pay?", "Where to go?", "Never used?", "Difficult to buy"], correct: 1, exp: "Aの返答が目的地なので、目的地を尋ねる質問を選びます。", cat: "過去問 大問3" },
            { id: "p3_06", type: "choice", q: "A: Where is that fish from?\nB: Tokushima. I try to buy local food.\nA: (               )\nB: Less distance means less impact on the environment.", a: ["Like fish?", "Is it famous?", "Problems?", "Why do you do that?"], correct: 3, exp: "理由を説明しているので、理由を問う質問が適切。", cat: "過去問 大問3" },
            { id: "p3_07", type: "choice", q: "A: Keiko, what's wrong?\nB: I lost the book you lent me.\nA: Don't worry. (               )\nB: Are you sure?", a: ["Need it for test", "Buy new one", "Have another copy", "Important book"], correct: 2, exp: "「心配しないで」と繋がる理由「もう一冊ある」が正解。", cat: "過去問 大問3" },
            { id: "p3_08", type: "choice", q: "A: What to do after graduation?\nB: Travel around Europe.\nA: (               )\nB: I hope to visit museums for free.", a: ["Why Europe?", "Good place?", "Been to America", "When leave?"], correct: 0, exp: "動機を聞く質問に対し、目的を答えています。", cat: "過去問 大問3" }
        ];

        const pastDataP4 = [
            {
                id: "p4_01",
                passage: `Do you use the Internet for shopping? It is certainly convenient. ${b('①')} on some websites, popular items are often sold out. Products might be sold out because of people ${b('②')} resellers. Resellers buy products at normal prices and then sell them later for higher prices. ${u('They', '③')} will resell anything, but popular categories for ${b('④')} are sneakers, trading cards, smartphones and toys.\n\nIn recent years, more and more people are reselling items. For some people, it is a full-time job and they can make a lot of money. Is reselling a positive or negative thing? This is a difficult question and many people have strong opinions about it. ${b('⑤')} most people are against reselling. They think that resellers buy products only to make a ${u('profit', '⑥')} not to use themselves. When ordinary people try to buy an item, it is already sold out. The only option is to pay a higher price on a flea market app.\n\nOn the other hand, some people think that resellers provide a valuable service. ${b('⑦')} when a popular new product is sold, people line up outside the shop to buy it. But for most of us, lining up is impossible—we are too busy with work or school. However, if resellers line up, buy ${u('the item', '⑧')} and then resell later, we have a chance to get the item, although the price is higher of course.\n\nWhat do you think? Are you for or against reselling? (⑨)\n\n<div class="annotation-box">ordinary：普通の / flea market app：フリマアプリ</div>`,
                questions: [
                    { id: "p4_01_1", type: "choice", q: "(1) 空所 ①, ⑤, ⑦ に入る適切な語の組み合わせを選べ。", a: ["① however / ⑤ Probably / ⑦ For example", "① therefore / ⑤ Usually / ⑦ Thus", "① however / ⑤ Therefore / ⑦ However", "① instead / ⑤ Probably / ⑦ Thus"], correct: 0, exp: "文脈判断問題。①逆接 ⑤推測 ⑦例示 です。", cat: "過去問 大問4" },
                    { id: "p4_01_2", type: "choice", q: "(2) 空所 ②, ④ に入る動詞の適切な形の組み合わせを選べ。", a: ["② calling / ④ reselling", "② called / ④ reselling", "② called / ④ resold", "② calling / ④ resell"], correct: 1, exp: "②呼ばれている人々(called) ④転売すること(reselling)のため。", cat: "過去問 大問4" },
                    { id: "p4_01_3", type: "choice", q: "(3) 下線部 ③ They の指す内容と ⑧ the item の具体的な単語数を選べ。", a: ["③ Resellers (1語) / ⑧ a popular new product (4語)", "③ Websites (1語) / ⑧ flea market app (3語)", "③ Products (1語) / ⑧ a lot of money (4語)", "③ Toys (1語) / ⑧ sneakers and cards (3語)"], correct: 0, exp: "指し示し問題。Resellers と a popular new product を指します。", cat: "過去問 大問4" },
                    { id: "p4_01_4", type: "choice", q: "(4) 下線部 ⑥ profit の意味として適切なものを選べ。", a: ["自慢", "企画", "満足", "利益"], correct: 3, exp: "make a profit で「利益をあげる」。", cat: "過去問 大問4" },
                    { id: "p4_01_5", type: "choice", q: "(5) 本文の内容と一致するものはどれか。", a: ["Resellers buy unpopular items at lower prices.", "Some items might be sold out because of resellers.", "Food products are popular and easy to resell.", "Most people are for reselling."], correct: 1, exp: "第1段落の内容と一致します。他は記述に反します。", cat: "過去問 大問4" }
                ]
            },
            {
                id: "p4_02",
                passage: `Though the construction industry has traditionally been seen as a man's world, ${u('the government and construction industry organizations are trying to make construction sites more woman-friendly', '①')}.\n\nIzumi Yamaguchi, 28, an employee of Shimizu Corp., works as a supervisor at a construction site... Among 16 supervisors at the building site, Yamaguchi is the only woman. ${b('②')} Yamaguchi wears a helmet, steel-toed shoes and a safety belt ${u('equipped with', '③')} a lifeline and other items around her waist.\n\nGeneral contractors have been making efforts to improve working conditions at construction sites by, for example, providing bathrooms and changing rooms ${u('exclusively', '④')} for women. They also have begun reforming personnel management systems... Kajima Corp. holds career consultations for female engineers. Junko Tsuchiyama, an official ${b('⑤')} the ${u('promotion', '⑥')} of diversity, said, "At today's more mechanized construction sites, women can play a larger role..."\n\n<div class="annotation-box">construction site：建設現場 / supervisor：監督 / personnel affairs：人事</div>`,
                questions: [
                    { id: "p4_02_1", type: "choice", q: "(1) 下線部 ① に関して企業がしている努力の具体例として適切なものは？", a: ["女性専用のトイレや更衣室の設置", "女性のみの建設現場の作成", "給与の倍増計画", "男性作業員の削減"], correct: 0, exp: "本文に「providing bathrooms and changing rooms exclusively for women」とあります。", cat: "過去問 大問4" },
                    { id: "p4_02_2", type: "choice", q: "(2) 空所 ②, ⑤ に入る最も適当なものは？", a: ["② On the job / ⑤ in charge of", "② In operation / ⑤ in terms of", "② While running / ⑤ in spite of", "② On the job / ⑤ in spite of"], correct: 0, exp: "現場仕事中（On the job）と、〜の担当（in charge of）です。", cat: "過去問 大問4" },
                    { id: "p4_02_3", type: "choice", q: "(3) 下線部 ③, ④, ⑥ と入れ替えてもほぼ同じ意味になるものは？", a: ["③ complete with / ④ entirely / ⑥ elevation", "③ occupied with / ④ individually / ⑥ publicity", "③ complete with / ④ additionally / ⑥ elevation", "③ in accordance with / ④ entirely / ⑥ advertisement"], correct: 0, exp: "語彙の言い換え問題です。", cat: "過去問 大問4" },
                    { id: "p4_02_4", type: "choice", q: "(4) 下線部 ⑦（記述）の変化の内容として正しい要約は？", a: ["働き方を変えることで男性も快適になり業界イメージが向上する", "女性だけが快適になれば業界イメージが向上する", "機械化が進むことで人間が不要になりイメージが向上する", "子供を育てる女性だけを優遇する"], correct: 0, exp: "土山さんの発言の後半部分をまとめた内容です。", cat: "過去問 大問4" }
                ]
            },
            {
                id: "p4_03",
                passage: `Do you know what your core values are? Core values are ${u('attributes', '①')} that are very important to you. For example, if you have a ${u('burning', '②')} desire to be number one, then working hard, doing your best, and ( ③ ) are likely to be some of your core values...\n\n"Here are the values that I ${u('stand for', '④')}: honesty, equality, kindness, compassion, treating people the way you want to be treated, and ( ⑤ ). To me, those are traditional values."\n\nYou can discover your own core values by asking yourself questions... Another way to discover your values is to look at what you do not like. For example, if you become irritated when people are late, then being on time, or ${b('⑥')} is one of your values. If seeing someone being bullied makes you angry, then compassion and ${b('⑦')} are important to you.\n\n<div class="annotation-box">attribute：特性 / punctuality：時間を守ること / fairness：公正さ</div>`,
                questions: [
                    { id: "p4_03_1", type: "choice", q: "(1) 下線部 ①, ②, ④ とほぼ同じ意味を表す語の組み合わせは？", a: ["① characteristics / ② passionate / ④ support", "① dreams / ② passionate / ④ mean", "① characteristics / ② flaming / ④ endure", "① virtues / ② aching / ④ support"], correct: 0, exp: "①属性 ②情熱的な ④支持する（理念とする）です。", cat: "過去問 大問4" },
                    { id: "p4_03_2", type: "choice", q: "(2)(3) 空所 ③, ⑤, ⑥, ⑦ に入る語句の組み合わせは？", a: ["③ achieving success / ⑤ helping those in need / ⑥ punctuality / ⑦ fairness", "③ reducing wastes / ⑤ achieving success / ⑥ excitement / ⑦ honesty", "③ achieving success / ⑤ honesty / ⑥ punctuality / ⑦ excitement", "③ working hard / ⑤ helping those / ⑥ fairness / ⑦ punctuality"], correct: 0, exp: "文脈と、文末の注釈も参考に判断します。", cat: "過去問 大問4" },
                    { id: "p4_03_3", type: "choice", q: "(4) 最初に述べられている価値観を知る方法は？", a: ["子供の頃好きだったことなどを自分に問いかける", "嫌いなものをリストアップする", "他人の価値観を真似してみる", "社会の期待に応える決断をする"], correct: 0, exp: "第3段落の冒頭に「discovery by asking yourself questions」とあります。", cat: "過去問 大問4" },
                    { id: "p4_03_4", type: "choice", q: "(5) 目標や決断は何に基づいてすべきと述べられているか？", a: ["自分の核となる価値観(Core values)", "社会の期待", "周囲の人の意見", "最新のトレンド"], correct: 0, exp: "最終段落に「Knowing your own core values will help to guide your actions」とあります。", cat: "過去問 大問4" }
                ]
            }
        ];

        // --- 模擬試験データ ---